
 CREATE DATABASE DB_PERUVIAN_PORTAL_TERRESTIAL_TRANSPORT;
 
 USE DB_PERUVIAN_PORTAL_TERRESTIAL_TRANSPORT;

 CREATE TABLE EMPRESA(
   ID_EMP       INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   RAZ_SOC_EMP  VARCHAR(50) NULL,
   RUC_EMP      VARCHAR(15) NULL,
   PAIS_EMP     VARCHAR(20) NULL,
   DEP_EMP      VARCHAR(50) NULL,
   DIR_EMP      VARCHAR(50) NULL,
   FONO_EMP     VARCHAR(10) NULL,
   MAIL_EMP     VARCHAR(50) NULL,
   USU_EMP      VARCHAR(20) NULL,
   PASS_EMP     VARCHAR(50) NULL,
   COD_CRED_EMP VARCHAR(20) NULL,
   FEC_EXP_EMP  DATE        NULL,
   EST_EMP      BOOLEAN
 );

 CREATE TABLE CLIENTE(    	
  ID_CLI        INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOM_CLI       VARCHAR(30) NULL,
  APE_CLI       VARCHAR(30) NULL,
  FEC_NAC_CLI   DATE        NULL,
  DIR_CLI       VARCHAR(50) NULL,
  FONO_CLI      VARCHAR(10) NULL,
  MAIL_CLI      VARCHAR(50) NULL,
  FOTO_CLI      VARCHAR(50) NULL,
  TIP_CLI       VARCHAR(20) NULL,
  USU_CLI       VARCHAR(10) NULL,
  PASS_CLI      VARCHAR(10) NULL,
  COD_CRED_CLI  VARCHAR(20) NULL,
  FEC_EXP_CLI   DATE        NULL,
  EST_CLI       BOOLEAN
 );

 CREATE TABLE EMPRESA_CLIENTE(
   ID_EMP_CLI   INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   ID_EMP       INT REFERENCES EMPRESA(ID_EMP) ON DELETE CASCADE,
   ID_CLI       INT REFERENCES CLIENTE(ID_CLI) ON DELETE CASCADE
 );

 CREATE TABLE PORTAL(
   ID_PTL       INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   URL_PTL      VARCHAR(50) NULL,
   EST_PTL      BOOLEAN,
   ID_EMP       INT REFERENCES TB_EMPRESAS(ID_EMP) ON DELETE CASCADE
 );

 CREATE TABLE INFORMACION(
   ID_INFO         INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   CABECERA_INFO   VARCHAR(50) NULL,
   TITU_PRI_INFO   VARCHAR(50) NULL,
   TEXTO_PRI_INFO  TEXT        NULL,
   LINK_PRI_INFO   VARCHAR(50) NULL,
   FOTO_PRI_INFO   VARCHAR(50) NULL,

   TITU_IZQ1_INFO  VARCHAR(50) NULL,
   TEXTO_IZQ1_INFO TEXT        NULL,
   LINK_IZQ1_INFO  VARCHAR(50) NULL,
   FOTO_IZQ1_INFO  VARCHAR(50) NULL,

   TITU_IZQ2_INFO  VARCHAR(50) NULL,
   TEXTO_IZQ2_INFO TEXT        NULL,
   LINK_IZQ2_INFO  VARCHAR(50) NULL,
   FOTO_IZQ2_INFO  VARCHAR(50) NULL,
   EST_INFO        BOOLEAN,
   ID_PTL          INT REFERENCES TB_PORTAL(ID_PTL) ON DELETE CASCADE
 );

 /** CLIENTE **/
 INSERT INTO CLIENTE (ID_CLI, NOM_CLI, APE_CLI, FEC_NAC_CLI, DIR_CLI, FONO_CLI, MAIL_CLI, FOTO_CLI, TIP_CLI, USU_CLI, PASS_CLI, COD_CRED_CLI, FEC_EXP_CLI, EST_CLI) values (1, 'Cesar Ricardo', 'Guerra Arnaiz', null, 'Av.Huaylas 356 dpt 7 chorillos', '45785659', 'cesarricardo_guerra19@hotmail.com', 'Ricardo.jpg', 'USUARIO', 'admin', 'admin', '12345678', null, '1');
 INSERT INTO CLIENTE (ID_CLI, NOM_CLI, APE_CLI, FEC_NAC_CLI, DIR_CLI, FONO_CLI, MAIL_CLI, FOTO_CLI, TIP_CLI, USU_CLI, PASS_CLI, COD_CRED_CLI, FEC_EXP_CLI, EST_CLI) values (2, 'Ivan Francisco', 'Silva Vera', null, 'Av La Calera 2345 Surco', '5784568', 'ivanarturof@hotmail.com', 'Ivan.jpg', 'USUARIO', '123', '123', '24682475', null, '1');

 /** EMPRESA **/
 INSERT INTO EMPRESA (ID_EMP, RAZ_SOC_EMP, RUC_EMP, PAIS_EMP, DEP_EMP, DIR_EMP, FONO_EMP, MAIL_EMP, USU_EMP, PASS_EMP, COD_CRED_EMP, FEC_EXP_EMP, EST_EMP) values (1, 'CRUZ DEL SUR', '57478556', 'Peru', 'Lima', 'Av.Arequipa 456 Lince', '548566698', 'cruzDelSur@yahoo.com', 'RGUERRA', 'SqrAquYuou8=', '9546878966', null, '1');
 
 /** EMPRESA_CLIENTE **/
 INSERT INTO EMPRESA_CLIENTE (ID_EMP_CLI, ID_EMP, ID_CLI) values (1, 1, 1);
 INSERT INTO EMPRESA_CLIENTE (ID_EMP_CLI, ID_EMP, ID_CLI) values (2, 1, 2);

 /** PORTAL **/
 INSERT INTO PORTAL(ID_PTL, URL_PTL, EST_PTL, ID_EMP) values (1, null, '1', 1);

 /** INFORMACION **/
 INSERT INTO INFORMACION (ID_INFO, CABECERA_INFO, TITU_PRI_INFO, TEXTO_PRI_INFO, LINK_PRI_INFO, FOTO_PRI_INFO, TITU_IZQ1_INFO, TEXTO_IZQ1_INFO, LINK_IZQ1_INFO, FOTO_IZQ1_INFO, TITU_IZQ2_INFO, TEXTO_IZQ2_INFO, LINK_IZQ2_INFO, FOTO_IZQ2_INFO, EST_INFO, ID_PTL) values (1, 'CabCruzDelSur.jpg', null, null, null, null, null, null, null, null, null, null, null, null, null, null);

 /* 
 INSERT INTO TB_USUARIOS( COD_USU, NOM_USU,APE_USU, DIRECCION_USU, CUMPLE_USU,DIREC_FOTO_USU,MAIL_USU,ID_USU,PASSWORD_USU,TIPO_USU,ESTADO_USU )
 VALUES
  ( 1, 'RICARDO', 'GUERRA', 'AV HUAYLAS 357 DPTO 7', '1983-04-10','Foto_Ricardo.gif','i220051@cibertec.edu.pe', 'RGUERRA', 'ADMIN',
    'ADMINISTRADOR', 'ENABLED' ),
  ( 2, 'JONATHAN', 'ROSALES', 'AV JOSE OLAYA 666', '1978-10-10', 'Foto_Jonathan.gif', 'Jhonathan@yahoo.com', 'JROSALES', 'ROSA',
    'MIEMBRO', 'ENABLED' );
 */
