
 CREATE DATABASE DB_PERUVIAN_PORTAL_TERRESTIAL_TRANSPORT;

 USE DB_PERUVIAN_PORTAL_TERRESTIAL_TRANSPORT;


 CREATE TABLE EMPRESA(
   ID_EMP       INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   RAZ_SOC_EMP  VARCHAR(50) NULL,
   RUC_EMP      VARCHAR(15) NULL,
   PAIS_EMP     DATETIME    NULL,
   DEP_EMP      VARCHAR(50) NULL,
   DIR_EMP      VARCHAR(50) NULL,
   FONO_EMP     VARCHAR(10) NULL,
   MAIL_EMP     VARCHAR(50) NULL,
   USU_EMP      VARCHAR(10) NULL,
   PASS_EMP     VARCHAR(10) NULL,
   EST_EMP      BOOLEAN
 );

 CREATE TABLE CLIENTE(    	
    ID_CLI        INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOM_CLI       VARCHAR(30) NULL,
	APE_CLI       VARCHAR(30) NULL,
	CUMP_CLI      DATETIME    NULL,
	DIR_CLI       VARCHAR(50) NULL,
    FONO_CLI      VARCHAR(10) NULL,
	MAIL_CLI      VARCHAR(50) NULL,
	FOTO_CLI      VARCHAR(50) NULL,
	TIP_CLI       VARCHAR(20) NULL,
	USU_CLI       VARCHAR(10) NULL,
	PASS_CLI      VARCHAR(10) NULL,
    EST_CLI       BOOLEAN
 );

 CREATE TABLE EMPRESA_CLIENTE(
    ID_EMP_CLI   INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_EMP       INT REFERENCES EMPRESA(ID_EMP) ON DELETE CASCADE,
    ID_CLI       INT REFERENCES CLIENTE(ID_CLI) ON DELETE CASCADE
 );

 CREATE TABLE PORTAL(
    ID_PTL       INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    URL_PTL      VARCHAR(50) NULL,
    CABECERA_PTL VARCHAR(50) NULL,
    EST_PTL      BOOLEAN,
    ID_EMP       INT REFERENCES TB_EMPRESAS(ID_EMP) ON DELETE CASCADE
 );

 CREATE TABLE INFORMACION(
   ID_INFO         INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   CABECERA_INFO   VARCHAR(50) NULL,
   TITU_PRI_INFO   VARCHAR(50) NULL,
   TEXTO_PRI_INFO  TEXT        NULL,
   LINK_PRI_INFO   VARCHAR(50) NULL,
   FOTO_PRI_INFO   VARCHAR(50) NULL,

   TITU_IZQ1_INFO  VARCHAR(50) NULL,
   TEXTO_IZQ1_INFO TEXT        NULL,
   LINK_IZQ1_INFO  VARCHAR(50) NULL,
   FOTO_IZQ1_INFO  VARCHAR(50) NULL,

   TITU_IZQ2_INFO  VARCHAR(50) NULL,
   TEXTO_IZQ2_INFO TEXT        NULL,
   LINK_IZQ2_INFO  VARCHAR(50) NULL,
   FOTO_IZQ2_INFO  VARCHAR(50) NULL,
   EST_INFO        BOOLEAN,
   ID_PTL          INT REFERENCES TB_PORTAL(ID_PTL) ON DELETE CASCADE
 );

 
 INSERT INTO TB_USUARIOS( COD_USU, NOM_USU,APE_USU, DIRECCION_USU, CUMPLE_USU,DIREC_FOTO_USU,MAIL_USU,ID_USU,PASSWORD_USU,TIPO_USU,ESTADO_USU )
 VALUES
  ( 1, 'RICARDO', 'GUERRA', 'AV HUAYLAS 357 DPTO 7', '1983-04-10','Foto_Ricardo.gif','i220051@cibertec.edu.pe', 'RGUERRA', 'ADMIN',
    'ADMINISTRADOR', 'ENABLED' ),
  ( 2, 'CARLOS', 'VERA', 'AV HUAYLAS 357 DPTO 7', '1983-04-10','Foto_Carlos.gif','i220051@cibertec.edu.pe', 'CVERA', 'ADMIN',
    'MIEMBRO', 'ENABLED' ),
  ( 3, 'JUAN', 'HUAMAN', 'AV HUAYLAS 357 DPTO 7', '1983-04-10','Foto_Juan.gif','i220051@cibertec.edu.pe', 'JHUAMAN', 'ADMIN',
    'MIEMBRO', 'ENABLED' ),
  ( 4, 'MARIO', 'GOMEZ', 'AV HUAYLAS 357 DPTO 7', '1983-04-10','Foto_Mario.gif','i220051@cibertec.edu.pe', 'MGOMEZ', 'ADMIN',
    'MIEMBRO', 'ENABLED' ),
  ( 5, 'JULIO', 'LA ROSA', 'AV HUAYLAS 357 DPTO 7', '1983-04-10','Foto_Julio.gif','i220051@cibertec.edu.pe', 'JLAROSA', 'ADMIN',
    'MIEMBRO', 'ENABLED' ),
  ( 6, 'CARLOS', 'CARLIN', 'AV HUAYLAS 357 DPTO 7', '1983-04-10','Foto_Carlos.gif','i220051@cibertec.edu.pe', 'CCARLIN', 'ADMIN',
    'MIEMBRO', 'ENABLED' ),
  ( 7, 'MILTON', 'BAUTISTA', 'AV HUAYLAS 357 DPTO 7', '1983-04-10','Foto_Milton.gif','i220051@cibertec.edu.pe', 'MBAUTISTA', 'ADMIN',
    'MIEMBRO', 'ENABLED' ),
  ( 8, 'MARCOS', 'RIVADENEIRA', 'AV HUAYLAS 357 DPTO 7', '1983-04-10','Foto_Marcos.gif','i220051@cibertec.edu.pe', 'MRIVADENERIA', 'ADMIN',
    'MIEMBRO', 'ENABLED' ),
  ( 9, 'DIEGO', 'TORRES', 'AV HUAYLAS 357 DPTO 7', '1983-04-10','Foto_Diego.gif','i220051@cibertec.edu.pe', 'DTORRES', 'ADMIN',
    'MIEMBRO', 'ENABLED' ),
  ( 10, 'JONATHAN', 'ROSALES', 'AV JOSE OLAYA 666', '1978-10-10', 'Foto_Jonathan.gif', 'Jhonathan@yahoo.com', 'JROSALES', 'ROSA',
    'MIEMBRO', 'ENABLED' );

